URLS = {
    "savelogin": {  # 持久化登录是否支持接口
        "req_url": "https://js.lgb360.com/lgb/logon/saveLogin.do",
        "req_type": "post",
        "re_try": 10,
        "re_time": 3,
        "s_time": 0.1,
        "is_json": True,
        "header": {
            "token": "",
            "memberId": "",
            "mobileTerminal": "0",
            "appversion": "3.5.4",
            "User-Agent": "LGB/3.5.4 (iPhone 12 Pro; iOS 16.3.1; zh_CN; 82f17147-23fd-422b-9c89-cfa1c2ed11ad; 2933677754)",
            "Content-Type": "application/x-www-form-urlencoded",
            "Host": "js.lgb360.com",
            "Connection": "Keep-Alive",
            "Accept-Encoding": "gzip"
        },
        # {"data":"SUCCESS","message":"成功","status":20000}
    },
    "login_check": {  # 检查是否登录
        "req_url": "https://aqy-adm.lgb360.com/aqy/stu/login/check?uidtok=mytoken&unionId=mymemberId",
        "req_type": "get",
        "re_try": 10,
        "re_time": 3,
        "s_time": 0.1,
        "is_json": True,
        "header": {
            "token": "",
            "memberId": "",
            "mobileTerminal": "0",
            "appversion": "3.5.4",
            "User-Agent": "LGB/3.5.4 (iPhone 12 Pro; iOS 16.3.1; zh_CN; 82f17147-23fd-422b-9c89-cfa1c2ed11ad; 2933677754)",
            "Content-Type": "application/x-www-form-urlencoded",
            "Host": "aqy-adm.lgb360.com",
            "Connection": "Keep-Alive",
            "Accept-Encoding": "gzip"
        },
        # {"message":"尚未登录","status":0}
        # {"message":"成功","status":20000}
    },
    "start": {  # 开始答题接口
        "req_url": "https://aqy-app.lgb360.com/aqy/ques/startCompetition",
        "req_type": "post",
        "re_try": 10,
        "re_time": 3,
        "s_time": 0.1,
        "is_json": True,
        "header": {
            "Host": "aqy-app.lgb360.com",
            "accept": "application/json, text/plain, */*",
            "token": "",
            "User-Agent": "",
            "memberId": "",
            "cookie": "",
            "content-type": "application/json;charset=UTF-8",
            "origin": "https://aqy-app.lgb360.com",
            "x-requested-with": "com.hxak.liangongbao",
            "sec-fetch-site": "same-origin",
            "sec-fetch-mode": "cors",
            "sec-fetch-dest": "empty",
            "accept-encoding": "gzip, deflate",
            "accept-language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7",
        },
    },
    "answer": {  # 回答问题接口
        "req_url": "https://aqy-app.lgb360.com/aqy/ques/answerQues",
        "req_type": "post",
        "re_try": 10,
        "re_time": 3,
        "s_time": 0.1,
        "is_json": True,
        "header": {
            "Host": "aqy-app.lgb360.com",
            "accept": "application/json, text/plain, */*",
            "token": "",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
            "memberId": "",
            "cookie": "",
            "content-type": "application/json;charset=UTF-8",
            "origin": "https://aqy-app.lgb360.com",
            "Referer": "https://aqy-app.lgb360.com/?memberId=&token=&mobile=",
            "accept-encoding": "gzip, deflate",
            "accept-language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7"
        },
    },
    "submitcompetition": {  # 答题结束提交接口
        "req_url": "https://aqy-app.lgb360.com/aqy/ques/submitCompetition",
        "req_type": "post",
        "re_try": 10,
        "re_time": 3,
        "s_time": 0.1,
        "is_json": True,
        "header": {
            "Host": "aqy-app.lgb360.com",
            "accept": "application/json, text/plain, */*",
            "token": "",
            "User-Agent": "",
            "memberId": "",
            "cookie": "",
            "content-type": "application/json;charset=UTF-8",
            "origin": "https://aqy-app.lgb360.com",
            "x-requested-with": "com.hxak.liangongbao",
            "sec-fetch-site": "same-origin",
            "sec-fetch-mode": "cors",
            "sec-fetch-dest": "empty",
            "accept-encoding": "gzip, deflate",
            "accept-language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7"
        },
    },
    "competition": {  # 查询接口
        "req_url": "https://aqy-app.lgb360.com/aqy/regist/competition",
        "req_type": "get",
        "re_try": 10,
        "re_time": 3,
        "s_time": 0.1,
        "is_json": True,
        "header": {
            "Host": "aqy-app.lgb360.com",
            "accept": "application/json, text/plain, */*",
            "token": "",
            "User-Agent": "",
            "memberId": "",
            "cookie": "",
            "content-type": "application/json;charset=UTF-8",
            "origin": "https://aqy-app.lgb360.com",
            "x-requested-with": "com.hxak.liangongbao",
            "sec-fetch-site": "same-origin",
            "sec-fetch-mode": "cors",
            "sec-fetch-dest": "empty",
            "accept-encoding": "gzip, deflate",
            "accept-language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7"
        },
    },
    "getrank": {  # 查询排名接口
        "req_url": "https://aqy-app.lgb360.com/aqy/score/getRank?date=mydate",
        "req_type": "post",
        "re_try": 10,
        "re_time": 3,
        "s_time": 0.1,
        "is_json": True,
        "header": {
            "Host": "aqy-app.lgb360.com",
            "accept": "application/json, text/plain, */*",
            "token": "",
            "User-Agent": "",
            "memberId": "",
            "cookie": "",
            "content-type": "application/json;charset=UTF-8",
            "origin": "https://aqy-app.lgb360.com",
            "x-requested-with": "com.hxak.liangongbao",
            "sec-fetch-site": "same-origin",
            "sec-fetch-mode": "cors",
            "sec-fetch-dest": "empty",
            "accept-encoding": "gzip, deflate",
            "accept-language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7"
        },
    },
    "getdrawsurplusnum": {  # 查询抽奖次数接口
        "req_url": "https://aqy-app.lgb360.com/aqy/prize/getDrawSurplusNum",
        "req_type": "post",
        "re_try": 10,
        "re_time": 3,
        "s_time": 0.1,
        "is_json": True,
        "header": {
            "Host": "aqy-app.lgb360.com",
            "accept": "application/json, text/plain, */*",
            "token": "",
            "User-Agent": "",
            "memberId": "",
            "cookie": "",
            "content-type": "application/json;charset=UTF-8",
            "origin": "https://aqy-app.lgb360.com",
            "x-requested-with": "com.hxak.liangongbao",
            "sec-fetch-site": "same-origin",
            "sec-fetch-mode": "cors",
            "sec-fetch-dest": "empty",
            "accept-encoding": "gzip, deflate",
            "accept-language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7"
        },
    },
    "drawprize": {  # 自动抽奖
        "req_url": "https://aqy-app.lgb360.com/aqy/prize/drawPrize",
        "req_type": "post",
        "re_try": 10,
        "re_time": 3,
        "s_time": 0.1,
        "is_json": True,
        "header": {
            "Host": "aqy-app.lgb360.com",
            "accept": "application/json, text/plain, */*",
            "token": "",
            "User-Agent": "",
            "memberId": "",
            "cookie": "",
            "content-type": "application/json;charset=UTF-8",
            "origin": "https://aqy-app.lgb360.com",
            "x-requested-with": "com.hxak.liangongbao",
            "sec-fetch-site": "same-origin",
            "sec-fetch-mode": "cors",
            "sec-fetch-dest": "empty",
            "accept-encoding": "gzip, deflate",
            "accept-language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7"
        },
    },
    "web_login": {
        "req_url": "https://aqy.lgb360.com/#/login",
        "re_try": 10,
    },
    "web_home": {
        "req_url": "https://aqy.lgb360.com/#/",
        "re_try": 10,
    },
    "web_answer": {
        "req_url": "https://aqy.lgb360.com/#/answer",
    },
    # 2023 API
    "wexin_request_qrcode":{
        "req_url": "https://open.weixin.qq.com/connect/qrconnect?appid=wx4411fdc32430ce58&scope=snsapi_login&redirect_uri=https%3A%2F%2Faqy.lgb360.com%2F%23%2Flogin&state=123456",
        "req_type": "get",
        "re_try": 10,
        "re_time": 3,
        "s_time": 0.1,
        "is_json": False,
        "header":{
            "Host": "open.weixin.qq.com",
            "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
            "Connection": "Keep-Alive",
            "sec-ch-ua": '"Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": "Windows",
            "content-type": "application/json;charset=UTF-8",
            "sec-fetch-site": "cross-site",
            "sec-fetch-mode": "navigate",
            "sec-fetch-dest": "iframe",
            "accept-encoding": "gzip, deflate, br",
            "accept-language": "zh-CN,zh;q=0.9,ja;q=0.8,en;q=0.7,ko;q=0.6",
            "Referer": "https://aqy.lgb360.com/"
        },
    },
    "wexin_request_uuid":{
        "req_url": "https://open.weixin.qq.com",
        "req_type": "get",
        "re_try": 10,
        "re_time": 3,
        "s_time": 0.1,
        "is_json": False,
        "not_decode": True,
        "header":{
            "Host": "open.weixin.qq.com",
            "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
            "Connection": "Keep-Alive",
            "sec-ch-ua": '"Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": "Windows",
            "content-type": "application/json;charset=UTF-8",
            "sec-fetch-site": "same-origin",
            "sec-fetch-mode": "no-cors",
            "sec-fetch-dest": "image",
            "accept-encoding": "gzip, deflate, br",
            "accept-language": "zh-CN,zh;q=0.9,ja;q=0.8,en;q=0.7,ko;q=0.6",
            "Referer": "https://open.weixin.qq.com/connect/qrconnect?appid=wx4411fdc32430ce58&scope=snsapi_login&redirect_uri=https%3A%2F%2Faqy.lgb360.com%2F%23%2Flogin&state=123456"
        },
    },
    "wexin_confirm_request_uuid":{
        "req_url": "https://open.weixin.qq.com/connect/confirm?uuid=",
    },
    "wexin_poll_confirm_request_uuid":{
        "req_url": "https://lp.open.weixin.qq.com/connect/l/qrconnect?uuid=",
        "req_type": "get",
        "re_try": 1,
        "re_time": 1,
        "s_time": 0.1,
        "is_json": False,
        "not_decode": False,
        "header":{
            "Host": "lp.open.weixin.qq.com",
            "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
            "Connection": "Keep-Alive",
            "sec-ch-ua": '"Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": "Windows",
            "content-type": "application/json;charset=UTF-8",
            "sec-fetch-site": "same-origin",
            "sec-fetch-mode": "no-cors",
            "sec-fetch-dest": "script",
            "accept-encoding": "gzip, deflate, br",
            "accept-language": "zh-CN,zh;q=0.9,ja;q=0.8,en;q=0.7,ko;q=0.6",
            "Referer": "https://open.weixin.qq.com/"
        },
    },
    "lgb2023_login":{
        "req_url": "https://aqy.lgb360.com/aqy/wechat/accountLogin?code=",
        "req_url_suffix": "&type=3",
        "req_type": "post",
        "re_try": 10,
        "re_time": 3,
        "s_time": 0.1,
        "is_json": True,
        "not_decode": False,
        "header":{
            "Host": "aqy.lgb360.com",
            "Origin": "https://aqy.lgb360.com",
            "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
            "Connection": "Keep-Alive",
            "sec-ch-ua": '"Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": "Windows",
            "content-type": "application/json;charset=UTF-8",
            "sec-fetch-site": "same-origin",
            "sec-fetch-mode": "cors",
            "sec-fetch-dest": "empty",
            "accept-encoding": "gzip, deflate, br",
            "accept-language": "zh-CN,zh;q=0.9,ja;q=0.8,en;q=0.7,ko;q=0.6",
            "Referer": "https://aqy.lgb360.com/"
        },
    },
    "lgb2023_competition":{
        "req_url": "https://aqy.lgb360.com/aqy/regist/competition",
        "req_type": "get",
        "re_try": 10,
        "re_time": 3,
        "s_time": 0.1,
        "is_json": True,
        "not_decode": False,
        "header":{
            "Host": "aqy.lgb360.com",
            "Origin": "https://aqy.lgb360.com",
            "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "token": "",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
            "memberId": "",
            "cookie": "",
            "Connection": "Keep-Alive",
            "sec-ch-ua": '"Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": "Windows",
            "content-type": "application/json;charset=UTF-8",
            "sec-fetch-site": "same-origin",
            "sec-fetch-mode": "cors",
            "sec-fetch-dest": "empty",
            "accept-encoding": "gzip, deflate, br",
            "accept-language": "zh-CN,zh;q=0.9,ja;q=0.8,en;q=0.7,ko;q=0.6",
            "Referer": "https://aqy.lgb360.com/"
        },
    },
    "lgb2023_start":{
        "req_url": "https://aqy.lgb360.com/aqy/ques/startCompetition",
        "req_type": "post",
        "re_try": 10,
        "re_time": 3,
        "s_time": 0.1,
        "is_json": True,
        "not_decode": False,
        "header":{
            "Host": "aqy.lgb360.com",
            "Origin": "https://aqy.lgb360.com",
            "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "token": "",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
            "memberId": "",
            "cookie": "",
            "Connection": "Keep-Alive",
            "sec-ch-ua": '"Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": "Windows",
            "content-type": "application/json;charset=UTF-8",
            "sec-fetch-site": "same-origin",
            "sec-fetch-mode": "cors",
            "sec-fetch-dest": "empty",
            "accept-encoding": "gzip, deflate, br",
            "accept-language": "zh-CN,zh;q=0.9,ja;q=0.8,en;q=0.7,ko;q=0.6",
            "Referer": "https://aqy.lgb360.com/"
        },
    },
    "lgb2023_answer": {
        "req_url": "https://aqy.lgb360.com/aqy/ques/answerQues",
        "req_type": "post",
        "re_try": 10,
        "re_time": 3,
        "s_time": 0.1,
        "is_json": True,
        "not_decode": False,
        "header":{
            "Host": "aqy.lgb360.com",
            "Origin": "https://aqy.lgb360.com",
            "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "token": "",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
            "memberId": "",
            "cookie": "",
            "Connection": "Keep-Alive",
            "sec-ch-ua": '"Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": "Windows",
            "content-type": "application/json;charset=UTF-8",
            "sec-fetch-site": "same-origin",
            "sec-fetch-mode": "cors",
            "sec-fetch-dest": "empty",
            "accept-encoding": "gzip, deflate, br",
            "accept-language": "zh-CN,zh;q=0.9,ja;q=0.8,en;q=0.7,ko;q=0.6",
            "Referer": "https://aqy.lgb360.com/"
        },
    },
    "lgb2023_submitcompetition": {  # 答题结束提交接口
        "req_url": "https://aqy.lgb360.com/aqy/ques/submitCompetition",
        "req_type": "post",
        "re_try": 10,
        "re_time": 3,
        "s_time": 0.1,
        "is_json": True,
        "header":{
            "Host": "aqy.lgb360.com",
            "Origin": "https://aqy.lgb360.com",
            "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "token": "",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
            "memberId": "",
            "cookie": "",
            "Connection": "Keep-Alive",
            "sec-ch-ua": '"Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": "Windows",
            "content-type": "application/json;charset=UTF-8",
            "sec-fetch-site": "same-origin",
            "sec-fetch-mode": "cors",
            "sec-fetch-dest": "empty",
            "accept-encoding": "gzip, deflate, br",
            "accept-language": "zh-CN,zh;q=0.9,ja;q=0.8,en;q=0.7,ko;q=0.6",
            "Referer": "https://aqy.lgb360.com/"
        },
    },
}
